import {
  siAnki,
  siAnthropic,
  siApple,
  siArxiv,
  siBluesky,
  siClaude,
  siCodecademy,
  siCoursera,
  siDiscord,
  siDropbox,
  siDuolingo,
  siEdx,
  siFacebook,
  siFigma,
  siGithub,
  siGitlab,
  siGmail,
  siGoogle,
  siGooglecalendar,
  siGoogleclassroom,
  siGoogledocs,
  siGoogledrive,
  siGooglegemini,
  siGooglemeet,
  siGooglescholar,
  siInstagram,
  siInstructure,
  siKhanacademy,
  siLeetcode,
  siMastodon,
  siMessenger,
  siMoodle,
  siNetflix,
  siNotion,
  siObsidian,
  siOverleaf,
  siPerplexity,
  siPinterest,
  siQuizlet,
  siReddit,
  siReplit,
  siSoundcloud,
  siSpotify,
  siStackoverflow,
  siTiktok,
  siTwitch,
  siUdemy,
  siWhatsapp,
  siWikipedia,
  siWolfram,
  siX,
  siYoutube,
  siYoutubemusic,
  siZoom,
  type SimpleIcon,
} from "simple-icons";

// Logos of well-known sites for the dashboard's Links widget, from Simple
// Icons (CC0). `domains` lets a link pick its logo automatically from its
// URL (see brandKeyForUrl in lib/dashboardLinks.ts). Only the logos listed
// here end up in the bundle.
export interface LinkBrand {
  key: string;
  label: string;
  icon: SimpleIcon;
  domains: readonly string[];
}

export const LINK_BRANDS: readonly LinkBrand[] = [
  { key: "youtube", label: "YouTube", icon: siYoutube, domains: ["youtube.com", "youtu.be"] },
  { key: "youtubemusic", label: "YouTube Music", icon: siYoutubemusic, domains: ["music.youtube.com"] },
  { key: "x", label: "X (Twitter)", icon: siX, domains: ["x.com", "twitter.com"] },
  { key: "reddit", label: "Reddit", icon: siReddit, domains: ["reddit.com", "redd.it"] },
  { key: "instagram", label: "Instagram", icon: siInstagram, domains: ["instagram.com"] },
  { key: "facebook", label: "Facebook", icon: siFacebook, domains: ["facebook.com", "fb.com"] },
  { key: "messenger", label: "Messenger", icon: siMessenger, domains: ["messenger.com"] },
  { key: "whatsapp", label: "WhatsApp", icon: siWhatsapp, domains: ["whatsapp.com"] },
  { key: "discord", label: "Discord", icon: siDiscord, domains: ["discord.com", "discord.gg"] },
  { key: "tiktok", label: "TikTok", icon: siTiktok, domains: ["tiktok.com"] },
  { key: "pinterest", label: "Pinterest", icon: siPinterest, domains: ["pinterest.com"] },
  { key: "bluesky", label: "Bluesky", icon: siBluesky, domains: ["bsky.app"] },
  { key: "mastodon", label: "Mastodon", icon: siMastodon, domains: ["mastodon.social"] },
  { key: "twitch", label: "Twitch", icon: siTwitch, domains: ["twitch.tv"] },
  { key: "spotify", label: "Spotify", icon: siSpotify, domains: ["spotify.com"] },
  { key: "soundcloud", label: "SoundCloud", icon: siSoundcloud, domains: ["soundcloud.com"] },
  { key: "netflix", label: "Netflix", icon: siNetflix, domains: ["netflix.com"] },
  { key: "google", label: "Google", icon: siGoogle, domains: ["google.com"] },
  { key: "gmail", label: "Gmail", icon: siGmail, domains: ["mail.google.com"] },
  { key: "googledrive", label: "Google Drive", icon: siGoogledrive, domains: ["drive.google.com"] },
  { key: "googledocs", label: "Google Docs", icon: siGoogledocs, domains: ["docs.google.com"] },
  { key: "googlecalendar", label: "Google Calendar", icon: siGooglecalendar, domains: ["calendar.google.com"] },
  { key: "googleclassroom", label: "Google Classroom", icon: siGoogleclassroom, domains: ["classroom.google.com"] },
  { key: "googlemeet", label: "Google Meet", icon: siGooglemeet, domains: ["meet.google.com"] },
  { key: "googlescholar", label: "Google Scholar", icon: siGooglescholar, domains: ["scholar.google.com"] },
  { key: "gemini", label: "Gemini", icon: siGooglegemini, domains: ["gemini.google.com"] },
  { key: "claude", label: "Claude", icon: siClaude, domains: ["claude.ai"] },
  { key: "anthropic", label: "Anthropic", icon: siAnthropic, domains: ["anthropic.com"] },
  { key: "perplexity", label: "Perplexity", icon: siPerplexity, domains: ["perplexity.ai"] },
  { key: "canvas", label: "Canvas", icon: siInstructure, domains: ["instructure.com"] },
  { key: "moodle", label: "Moodle", icon: siMoodle, domains: ["moodle.org", "moodle.com"] },
  { key: "khanacademy", label: "Khan Academy", icon: siKhanacademy, domains: ["khanacademy.org"] },
  { key: "coursera", label: "Coursera", icon: siCoursera, domains: ["coursera.org"] },
  { key: "edx", label: "edX", icon: siEdx, domains: ["edx.org"] },
  { key: "udemy", label: "Udemy", icon: siUdemy, domains: ["udemy.com"] },
  { key: "codecademy", label: "Codecademy", icon: siCodecademy, domains: ["codecademy.com"] },
  { key: "duolingo", label: "Duolingo", icon: siDuolingo, domains: ["duolingo.com"] },
  { key: "quizlet", label: "Quizlet", icon: siQuizlet, domains: ["quizlet.com"] },
  { key: "anki", label: "Anki", icon: siAnki, domains: ["ankiweb.net", "apps.ankiweb.net"] },
  { key: "wikipedia", label: "Wikipedia", icon: siWikipedia, domains: ["wikipedia.org"] },
  { key: "wolfram", label: "Wolfram|Alpha", icon: siWolfram, domains: ["wolframalpha.com", "wolfram.com"] },
  { key: "arxiv", label: "arXiv", icon: siArxiv, domains: ["arxiv.org"] },
  { key: "overleaf", label: "Overleaf", icon: siOverleaf, domains: ["overleaf.com"] },
  { key: "notion", label: "Notion", icon: siNotion, domains: ["notion.so", "notion.com"] },
  { key: "obsidian", label: "Obsidian", icon: siObsidian, domains: ["obsidian.md"] },
  { key: "github", label: "GitHub", icon: siGithub, domains: ["github.com"] },
  { key: "gitlab", label: "GitLab", icon: siGitlab, domains: ["gitlab.com"] },
  { key: "stackoverflow", label: "Stack Overflow", icon: siStackoverflow, domains: ["stackoverflow.com"] },
  { key: "leetcode", label: "LeetCode", icon: siLeetcode, domains: ["leetcode.com"] },
  { key: "replit", label: "Replit", icon: siReplit, domains: ["replit.com"] },
  { key: "figma", label: "Figma", icon: siFigma, domains: ["figma.com"] },
  { key: "dropbox", label: "Dropbox", icon: siDropbox, domains: ["dropbox.com"] },
  { key: "zoom", label: "Zoom", icon: siZoom, domains: ["zoom.us"] },
  { key: "apple", label: "Apple", icon: siApple, domains: ["apple.com"] },
];

export const LINK_BRAND_KEYS: ReadonlySet<string> = new Set(LINK_BRANDS.map((b) => b.key));

export function linkBrand(key: string): LinkBrand | undefined {
  return LINK_BRANDS.find((b) => b.key === key);
}
